#### ML Fundamentals Day_38
***
- Support Vector Machine
    - Support Vector Classifier (SVC)
    - Supprt Vector Regressor (SVR)

##### Support Vector Classifier (SVC)

In [2]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [4]:
df = datasets.load_iris(as_frame=True).frame

In [5]:
df.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [6]:
df.shape

(150, 5)

In [7]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [ ]:
X = df.drop("target",axis=1)
y = df["target"]

In [9]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
X_train,X_test,y_train,y_test = train_test_split(
     X,y,test_size=0.3,random_state=42,stratify=y
)

In [11]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
## Model
svc = SVC()
svc.fit(X_train_scaled,y_train)

SVC()

In [15]:
y_pred = svc.predict(X_test_scaled)

In [18]:
## Evaluate Model
from sklearn.metrics import accuracy_score,classification_report

print("accuracy:",accuracy_score(y_test,y_pred))
print("classification report:",classification_report(y_test,y_pred))

accuracy: 0.9333333333333333
classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [20]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, average='weighted')
print("F1 Score:", f1)

F1 Score: 0.9332591768631814

In [21]:
## Linear Kernel
svc = SVC(kernel="linear")
svc.fit(X_train_scaled,y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 0.9111111111111111

In [23]:
## Polynomial Kernel
svc = SVC(kernel="poly")
svc.fit(X_train_scaled,y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 0.8666666666666667

In [24]:
## Sigmoid Kernel
svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled,y_train)

y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 0.9111111111111111

In [25]:
c_vals = [0.5,1,2,3,4,5]

for val in c_vals:
     svc = SVC(C=val,kernel="rbf")
     svc.fit(X_train_scaled,y_train)

     y_pred = svc.predict(X_test_scaled)
     print(f"C: {val} & accuracy: {accuracy_score(y_test,y_pred)}")

C: 0.5 & accuracy: 0.9111111111111111
C: 1 & accuracy: 0.9333333333333333
C: 2 & accuracy: 0.9111111111111111
C: 3 & accuracy: 0.9111111111111111
C: 4 & accuracy: 0.9333333333333333
C: 5 & accuracy: 0.9333333333333333

****

#### ML Fundamentals Day_39
- Support Vector Regressor (SVR)

In [27]:
from sklearn.svm import SVR
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn import datasets

In [28]:
df = datasets.load_diabetes(as_frame=True).frame

In [29]:
df.head()

        age       sex       bmi        bp  ...        s4        s5        s6  target
0  0.038076  0.050680  0.061696  0.021872  ... -0.002592  0.019907 -0.017646   151.0
1 -0.001882 -0.044642 -0.051474 -0.026328  ... -0.039493 -0.068332 -0.092204    75.0
2  0.085299  0.050680  0.044451 -0.005670  ... -0.002592  0.002861 -0.025930   141.0
3 -0.089063 -0.044642 -0.011595 -0.036656  ...  0.034309  0.022688 -0.009362   206.0
4  0.005383 -0.044642 -0.036385  0.021872  ... -0.002592 -0.031988 -0.046641   135.0

[5 rows x 11 columns]

In [30]:
df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [31]:
X = df.drop("target",axis=1)
y = df["target"]

In [33]:
X.head()

        age       sex       bmi  ...        s4        s5        s6
0  0.038076  0.050680  0.061696  ... -0.002592  0.019907 -0.017646
1 -0.001882 -0.044642 -0.051474  ... -0.039493 -0.068332 -0.092204
2  0.085299  0.050680  0.044451  ... -0.002592  0.002861 -0.025930
3 -0.089063 -0.044642 -0.011595  ...  0.034309  0.022688 -0.009362
4  0.005383 -0.044642 -0.036385  ... -0.002592 -0.031988 -0.046641

[5 rows x 10 columns]

In [34]:
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: target, dtype: float64

In [36]:
X_train,X_test,y_train,y_test = train_test_split(
     X,y,test_size=0.3,random_state=42
)

In [37]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: target, Length: 442, dtype: float64

In [39]:
y_train.values.reshape(-1,1)

array([[208.],
       [261.],
       [179.],
       [258.],
       [262.],
       [ 51.],
       [237.],
       [ 71.],
       [139.],
       [268.],
       [ 69.],
       [317.],
       [249.],
       [154.],
       [192.],
       [116.],
       [ 81.],
       [122.],
       [259.],
       [191.],
       [292.],
       [ 55.],
       [107.],
       [210.],
       [ 91.],
       [253.],
       [ 85.],
       [252.],
       [ 59.],
       [ 78.],
       [200.],
       [ 78.],
       [245.],
       [175.],
       [ 42.],
       [127.],
       [ 53.],
       [ 94.],
       [104.],
       [199.],
       [265.],
       [281.],
       [248.],
       [257.],
       [215.],
       [303.],
       [170.],
       [ 59.],
       [277.],
       [209.],
       [138.],
       [198.],
       [124.],
       [ 96.],
       [288.],
       [225.],
       [265.],
       [101.],
       [ 55.],
       [198.],
       [ 51.],
       [252.],
       [ 64.],
       [220.],
       [131.],
       [212.],
       [142.],
       [103.],
       [155.],
       [121.],
       [ 86.],
       [111.],
       [ 65.],
       [131.],
       [ 51.],
       [128.],
       [141.],
       [ 48.],
       [109.],
       [178.],
       [ 88.],
       [ 84.],
       [216.],
       [150.],
       [ 60.],
       [ 96.],
       [190.],
       [ 74.],
       [279.],
       [182.],
       [160.],
       [245.],
       [276.],
       [174.],
       [180.],
       [150.],
       [196.],
       [138.],
       [ 97.],
       [246.],
       [321.],
       [308.],
       [109.],
       [ 69.],
       [182.],
       [258.],
       [161.],
       [178.],
       [214.],
       [ 45.],
       [150.],
       [160.],
       [ 55.],
       [197.],
       [185.],
       [268.],
       [310.],
       [123.],
       [ 68.],
       [ 72.],
       [185.],
       [144.],
       [147.],
       [168.],
       [178.],
       [246.],
       [151.],
       [127.],
       [ 83.],
       [332.],
       [152.],
       [109.],
       [ 90.],
       [ 66.],
       [214.],
       [ 85.],
       [129.],
       [ 89.],
       [259.],
       [229.],
       [200.],
       [ 77.],
       [ 54.],
       [ 31.],
       [109.],
       [206.],
       [144.],
       [118.],
       [ 83.],
       [242.],
       [259.],
       [ 72.],
       [163.],
       [181.],
       [141.],
       [ 71.],
       [137.],
       [195.],
       [179.],
       [102.],
       [131.],
       [ 47.],
       [235.],
       [ 77.],
       [198.],
       [ 93.],
       [162.],
       [225.],
       [275.],
       [183.],
       [306.],
       [ 81.],
       [ 55.],
       [146.],
       [196.],
       [230.],
       [310.],
       [ 40.],
       [135.],
       [346.],
       [ 43.],
       [128.],
       [ 77.],
       [235.],
       [ 49.],
       [ 74.],
       [ 92.],
       [ 84.],
       [263.],
       [144.],
       [142.],
       [341.],
       [115.],
       [158.],
       [273.],
       [ 85.],
       [ 88.],
       [220.],
       [ 39.],
       [ 80.],
       [172.],
       [217.],
       [336.],
       [ 52.],
       [272.],
       [115.],
       [110.],
       [131.],
       [ 71.],
       [275.],
       [118.],
       [ 25.],
       [100.],
       [281.],
       [221.],
       [248.],
       [200.],
       [132.],
       [ 91.],
       [ 67.],
       [202.],
       [ 73.],
       [ 85.],
       [275.],
       [243.],
       [ 66.],
       [293.],
       [236.],
       [243.],
       [ 87.],
       [ 39.],
       [217.],
       [ 92.],
       [296.],
       [292.],
       [142.],
       [ 50.],
       [ 53.],
       [104.],
       [ 75.],
       [120.],
       [142.],
       [143.],
       [ 99.],
       [ 65.],
       [116.],
       [233.],
       [164.],
       [ 95.],
       [ 59.],
       [139.],
       [145.],
       [177.],
       [185.],
       [ 97.],
       [ 42.],
       [201.],
       [241.],
       [ 70.],
       [ 78.],
       [ 49.],
       [103.],
       [ 44.],
       [111.],
       [191.],
       [ 47.],
       [182.],
       [ 58.],
       [155.],
       [151.],
       [ 79.],
       [104.],
       [143.],
       [152.],
       [170.],
       [ 75.],
       [200.],
       [124.],
       [ 91.],
       [ 49.],
       [163.],
       [ 53.],
       [283.],
       [178.],
       [219.],
       [200.],
       [113.],
       [113.],
       [ 63.],
       [114.],
       [126.],
       [274.],
       [ 88.],
       [311.],
       [ 83.],
       [ 71.],
       [134.],
       [244.],
       [ 65.],
       [173.],
       [ 57.],
       [ 68.],
       [141.],
       [270.],
       [134.],
       [202.],
       [148.],
       [ 64.],
       [302.]])

In [41]:
y_scaler = StandardScaler()

y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test_scaled = y_scaler.fit_transform(y_test.values.reshape(-1,1)).ravel()

In [46]:
model = SVR()
model.fit(X_train,y_train_scaled)

SVR()

In [47]:
y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

In [50]:
print("Train r2: ",r2_score(y_train_scaled,y_train_pred_scaled))
print("Test r2: ",r2_score(y_test_scaled,y_test_pred_scaled))

Train r2:  0.6596361676267714
Test r2:  0.4808287850481273

In [51]:
## Linear Kernel
model = SVR(kernel="linear")
model.fit(X_train,y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("Train r2: ",r2_score(y_train_scaled,y_train_pred_scaled))
print("Test r2: ",r2_score(y_test_scaled,y_test_pred_scaled))

Train r2:  0.45191229982475256
Test r2:  0.41295430606006556

In [ ]:
## Polynomial Kernel (overfitting)
model = SVR(kernel="poly")
model.fit(X_train,y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("Train r2: ",r2_score(y_train_scaled,y_train_pred_scaled))
print("Test r2: ",r2_score(y_test_scaled,y_test_pred_scaled))

Train r2:  0.5790920834310542
Test r2:  0.2496489598680388

In [54]:
## Sigmoid Kernel (Not Good For Used)
model = SVR(kernel="sigmoid")
model.fit(X_train,y_train_scaled)

y_test_pred_scaled = model.predict(X_test)
y_train_pred_scaled = model.predict(X_train)

print("Train r2: ",r2_score(y_train_scaled,y_train_pred_scaled))
print("Test r2: ",r2_score(y_test_scaled,y_test_pred_scaled))

Train r2:  -19.721193440731312
Test r2:  -13.334780649499326

- Hyperparameter Tuning Using GridSearchCV

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
param_grid = {
     "C":[1,2,5,10,50,100],
     "kernel":["rbf","linear"],
     "epsilon":[0.01,0.1,0.2,0.3,0.5]
}

In [57]:
svr = SVR()
grid_search = GridSearchCV(svr,param_grid,scoring="r2",cv=5)
grid_search.fit(X_train,y_train_scaled)

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 5, 10, 50, 100],
                         'epsilon': [0.01, 0.1, 0.2, 0.3, 0.5],
                         'kernel': ['rbf', 'linear']},
             scoring='r2')

In [58]:
print("best params: ",grid_search.best_params_)

best params:  {'C': 10, 'epsilon': 0.1, 'kernel': 'linear'}

In [64]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

best_model = SVR(kernel="linear", C=10, epsilon=0.1)
best_model.fit(X_train, y_train_scaled)

y_train_pred_scaled = best_model.predict(X_train)
y_test_pred_scaled = best_model.predict(X_test)

print("Train R2:", r2_score(y_train_scaled, y_train_pred_scaled))
print("Test R2:", r2_score(y_test_scaled, y_test_pred_scaled))

Train R2: 0.5151066486918876
Test R2: 0.4566330687447978

In [67]:
from sklearn.svm import LinearSVR
from sklearn.metrics import r2_score

model = LinearSVR(
    C=10,
    epsilon=0.1,
    max_iter=5000,
    random_state=42
)

model.fit(X_train, y_train_scaled)

y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)

print("Train R2:", r2_score(y_train_scaled, y_train_pred_scaled))
print("Test R2:", r2_score(y_test_scaled, y_test_pred_scaled))

Train R2: 0.515263897671951
Test R2: 0.4568079769876431