- Indian Employee Dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("indian_employee_data.csv")
df.head()

,Emp_ID,Name,Age,Salary_INR,Experience_Years,City,Department,Performance_Rating
0,101,Amit Sharma,27,650000.0,4.0,Delhi,IT,4.5
1,102,Riya Gupta,32,NaN,8.0,Mumbai,HR,3.8
2,103,Rajesh Verma,45,1200000.0,NaN,Bangalore,Finance,4.9
3,104,Priya Singh,29,720000.0,6.0,Kolkata,IT,4.2
4,105,Sunil Kumar,26,500000.0,3.0,Chennai,Sales,NaN

In [3]:
## Missing value
df.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary_INR            4
Experience_Years      1
City                  0
Department            0
Performance_Rating    1
dtype: int64

In [4]:
df['Experience_Years'].fillna(df['Experience_Years'].mean(),inplace=True)
df['Performance_Rating'].fillna(df['Performance_Rating'].mean(),inplace=True)
df['Salary_INR'].fillna(df['Salary_INR'].mean(),inplace=True)

C:\Users\gzbra\AppData\Local\Temp\ipykernel_23136\3012552323.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Experience_Years'].fillna(df['Experience_Years'].mean(),inplace=True)
C:\Users\gzbra\AppData\Local\Temp\ipykernel_23136\3012552323.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Rating'].fillna(df['Performance_Rating'].mean(),inplace=True)
C:\Users\gzbra\AppData\Local\Temp\ipykernel_23136\3012552323.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary_INR'].fillna(df['Salary_INR'].mean(),inplace=True)

In [6]:
df.replace([np.inf,-np.inf],np.nan,inplace=True)

In [7]:
## remove duplicates
df.drop_duplicates(inplace=True)

In [9]:
## replace negative salary
df['Salary_INR'] = np.where(df['Salary_INR']<0,df['Salary_INR'].mean(),df['Salary_INR'])

In [10]:
sal_mean = df['Salary_INR'].mean()
sal_std = df['Salary_INR'].std()
lower = sal_mean - (3*sal_std)
upper = sal_mean + (3*sal_std)

In [11]:
## remove rows where salary to high or to low
df = df[(df['Salary_INR'] >=lower) & (df['Salary_INR']<=upper)]
df.to_csv("cleaned_data.csv",index=False)
print("Data Cleaning Completed..!")

Data Cleaning Completed..!

In [12]:
## check cleaned data
import pandas as pd
df = pd.read_csv('cleaned_data.csv')
df.head()

,Emp_ID,Name,Age,Salary_INR,Experience_Years,City,Department,Performance_Rating
0,101,Amit Sharma,27,6.500000e+05,4.000000,Delhi,IT,4.500000
1,102,Riya Gupta,32,1.257857e+06,8.000000,Mumbai,HR,3.800000
2,103,Rajesh Verma,45,1.200000e+06,11.208333,Bangalore,Finance,4.900000
3,104,Priya Singh,29,7.200000e+05,6.000000,Kolkata,IT,4.200000
4,105,Sunil Kumar,26,5.000000e+05,3.000000,Chennai,Sales,4.345833

In [13]:
df.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary_INR            0
Experience_Years      0
City                  0
Department            0
Performance_Rating    0
dtype: int64